#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2022/01/19 07:54:19
# Search URL: https://esgf-node.llnl.gov/esg-search/wget/?distrib=false&dataset_id=cmip5.output1.MPI-M.MPI-ESM-MR.rcp85.day.ocean.day.r1i1p1.v20120503|aims3.llnl.gov
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.llnl.gov/esg-search/wget/?distrib=false&dataset_id=cmip5.output1.MPI-M.MPI-ESM-MR.rcp85.day.ocean.day.r1i1p1.v20120503|aims3.llnl.gov'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20060101-20061231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20060101-20061231.nc' 'SHA256' 'bc18ffad67c9a6fa3d0d29d1242583cc201ee3f8ef7697b3666a824e664e7b38'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20070101-20071231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20070101-20071231.nc' 'SHA256' 'd3ecaa363de4936e6925fae8b1b8103de6bbf0cde9ed806b2756dda1d6f449b1'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20080101-20081231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20080101-20081231.nc' 'SHA256' '114032bd866a1484937dcd730a57560178c716d3ca0f09c0dee40e3ea78a2b14'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20090101-20091231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20090101-20091231.nc' 'SHA256' '6e4f9cd4da224792038583fcc07b9af79289bab26b199235da3d73d574971f65'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20100101-20101231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20100101-20101231.nc' 'SHA256' 'b86ff23c81f7865bd68b444d6431bdeee31e9ac87a018b4deef04a665a849e35'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20110101-20111231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20110101-20111231.nc' 'SHA256' 'eb9da689bc259cb850d83c1e358f545d99fa9240f17709fcd685863b97f3eb1b'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20120101-20121231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20120101-20121231.nc' 'SHA256' '445c7f2ef04065ed7838822c5b636cdee8fe77c5be8b7bb762eba737263b57aa'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20130101-20131231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20130101-20131231.nc' 'SHA256' '8ad68d3b43ab4853b6adb52ecb2deaef3d73a6f107435e074be0936b5108aa50'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20140101-20141231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20140101-20141231.nc' 'SHA256' '19aa3fe8942510b54fa4548ea3dc12a9d78d8bf1b5242640390f96d52b1aa724'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20150101-20151231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20150101-20151231.nc' 'SHA256' '39a585f57e89172f946c7ccb3d7ab9b8180dc24b977fa980b4294c02e2590d33'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20160101-20161231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20160101-20161231.nc' 'SHA256' '6053461421002aec4a94716aa1448cf892d3acfcf1ba8ca20709b4702ff390bb'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20170101-20171231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20170101-20171231.nc' 'SHA256' 'd2b89a8f0878649304716c1fa53e24533b43ec8dd58835ed84af98074428da98'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20180101-20181231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20180101-20181231.nc' 'SHA256' 'b321375ec346c16062856361a0074c75d8ec99e99b73faa249fbe9505a6d4dbe'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20190101-20191231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20190101-20191231.nc' 'SHA256' '543e3ca9478d4343bb1b67c6e0e5a1b4dc994d0d5a5fdf2ff5dd10319d186f98'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20200101-20201231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20200101-20201231.nc' 'SHA256' 'e66a416296bc2fb679cb03fa9c41b4aa3cf6ea94fd2ab619119d72848de394c0'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20210101-20211231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20210101-20211231.nc' 'SHA256' '117b53e7f33de8ee8c1f6be0a2966abe8d32f810e0127d733f1bd667d697d89f'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20220101-20221231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20220101-20221231.nc' 'SHA256' 'd22b557c47d49616e7d33480778bc019160cb7141fbbeb8b13cbec5220b75536'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20230101-20231231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20230101-20231231.nc' 'SHA256' '408ee50cc6e7071cf7ca2b79266158ef8374194dadc8c282c2a96b89a88884ed'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20240101-20241231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20240101-20241231.nc' 'SHA256' 'b59389d5d3a88ea3f672f880e6a3de30d2d3dd99cddde6e9bcf2db79e801145b'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20250101-20251231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20250101-20251231.nc' 'SHA256' 'dbfa781e7156436b2a3eaa54f53106a5f8a0f366c0b941c3efb49577fbb354c9'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20260101-20261231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20260101-20261231.nc' 'SHA256' '8a4974ab29e7214a880b8a47c1db0355f5a380adfd2ecf1ee1440e4fc15e75a5'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20270101-20271231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20270101-20271231.nc' 'SHA256' '7ad85dda48ec65b124bfb4b7c4d1b7272a0fd6a7ee3d351876f011f687af6ac9'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20280101-20281231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20280101-20281231.nc' 'SHA256' '87f6cc3d5623d4e371a8a8def2541903cf25e2815cd68b2b436f011fbde103aa'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20290101-20291231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20290101-20291231.nc' 'SHA256' '3f960efbadbac46d5e4a6748f8c40600b3aee3aba1a69ef4e04d94c306ea7836'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20300101-20301231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20300101-20301231.nc' 'SHA256' 'f5079e10831f3212c582755b7dda481a8731439a00d447199db59efb0cb435c8'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20310101-20311231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20310101-20311231.nc' 'SHA256' 'c99887ee4934137494e4ee8dc36b66a4f8ce3af5b95223e8fc8430aad15b5a48'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20320101-20321231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20320101-20321231.nc' 'SHA256' '87e253e999b25af43b3a4459f5b7d89943690c89208672021de5502199526c5c'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20330101-20331231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20330101-20331231.nc' 'SHA256' '40a176efa87828558931c01bac6bcccde3bf47ed151d9939e76a1ee5fcc35d76'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20340101-20341231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20340101-20341231.nc' 'SHA256' '85453c3860ff6c8556d94ef6119160b7bba6ec5fb9bef83a5e2786bb5a39f730'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20350101-20351231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20350101-20351231.nc' 'SHA256' '01acb1561367a2b3dd75d7c0d966526d37d5c9fe69aef3e77954ddf70bb3882a'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20360101-20361231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20360101-20361231.nc' 'SHA256' '737b13f93f14356dfbccef7801567eeafc70a99b2291eca921bcd4e68612a4cd'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20370101-20371231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20370101-20371231.nc' 'SHA256' '9d41d088db2d4de5c379d8239fa326ac296fdfc1a05262065f732db917e8124f'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20380101-20381231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20380101-20381231.nc' 'SHA256' 'c1b87595064a00a2dd6b20ba15f782751fc64a842b0f7c8a7dd7600d8d7cab78'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20390101-20391231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20390101-20391231.nc' 'SHA256' '241ceef07e1d74288b9d96ba3eb111277e26fbc8f57968b8582d9eb8664f85d0'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20400101-20401231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20400101-20401231.nc' 'SHA256' '56196353f0e313c02c02d5ac99b6d6e6c908a1c6a4830ea5ae62272878114ac6'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20410101-20411231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20410101-20411231.nc' 'SHA256' '2750f4f20f91ff615e1bba3a4de3650e1bc80433e8ff06982267aba01b0613ef'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20420101-20421231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20420101-20421231.nc' 'SHA256' '022f9840405636ea552c96d9b2b6a7925f02126733970b072c176f5ecc27b201'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20430101-20431231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20430101-20431231.nc' 'SHA256' 'd6cf4cd9504c14e62c026c331f50d712ea60b8638079c32ae41aa390077839e4'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20440101-20441231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20440101-20441231.nc' 'SHA256' '0e1ec1a3d3a3e49781fd762b3b566a103f7107ecfa1bf9bd6e8fbb0eecd9de43'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20450101-20451231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20450101-20451231.nc' 'SHA256' '5172a69c16927e6b4be9a215bd455296352888a0eb828f0ffa5e267150a26d14'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20460101-20461231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20460101-20461231.nc' 'SHA256' 'efb18798b0f787ab55bd8c40d6a26dfeeaf16be375076bffb42cdbebbd1c07bd'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20470101-20471231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20470101-20471231.nc' 'SHA256' 'b491788392847e28b002cd3eb155a7743b7d7d0a1cbd4096d9f5d462978e6302'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20480101-20481231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20480101-20481231.nc' 'SHA256' '8d10e79b6efb7ae0f29fe2a8729e419aa351b98b6f1782358f517cbb58238ced'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20490101-20491231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20490101-20491231.nc' 'SHA256' '6cf3e4905016ec9e1fe7f6f2c7a7869afb19270edc4e68bdb8b586a94e20d137'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20500101-20501231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20500101-20501231.nc' 'SHA256' '06df2dd78bd3ba8240a16a93b2e19fabcd2615f93cd142f0513fab311fdb0ab3'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20510101-20511231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20510101-20511231.nc' 'SHA256' '4a621fc667d720159671c3a123dd1c1ce4ec66df870480b8ac0d338736f61ac5'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20520101-20521231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20520101-20521231.nc' 'SHA256' 'a41e4a1622ebd4b7d5484558360d7446134a8d9955b02db9cb1b67b5b8652d8b'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20530101-20531231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20530101-20531231.nc' 'SHA256' 'ee41ed1d3118f81d912d0c7c4fdb0d589f58d487478294f7beeb107b5c489881'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20540101-20541231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20540101-20541231.nc' 'SHA256' 'eef64f7369709ef6c4e848509a8dc21ceeb231c045e6cd34e2c42aafd2f18ae5'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20550101-20551231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20550101-20551231.nc' 'SHA256' '287232c1d660533d6e651e31e2b21c57fc1752c8fbddc9b3d82b52930c9bd4ec'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20560101-20561231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20560101-20561231.nc' 'SHA256' 'f3d373403429ab4bcb2ed0c9a1c9a098071ea0ac20e2e4780887de9adbb076ca'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20570101-20571231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20570101-20571231.nc' 'SHA256' '60541a6b671afb1993806f78f19f6608c881709ddca12edb5b0e10d059dfe048'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20580101-20581231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20580101-20581231.nc' 'SHA256' '140388c23a12cbd1dd52da7411d5b2922dedeb4d2627027dd504fe59d5678d05'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20590101-20591231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20590101-20591231.nc' 'SHA256' '364c390f186fd24218103a6107d84bab8df3bc98230fbeeda739f152817a9459'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20600101-20601231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20600101-20601231.nc' 'SHA256' 'bce07132deaeb48ebbaadb650d83d595fa7cc61d940aa20d28b74e9f0a40b821'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20610101-20611231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20610101-20611231.nc' 'SHA256' 'a50cea88b3d7f121cc6761af716918724cbb074532d517a6e5ae39523328aca6'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20620101-20621231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20620101-20621231.nc' 'SHA256' '71a707b802a3b26d15c8638ac75d3acb6a19088e9ceb3372dba89e6c57f5da7b'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20630101-20631231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20630101-20631231.nc' 'SHA256' '59bd30291f933fd2cdc1458ea5b7cb34e188a6d611380e627e378eb56c26dccc'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20640101-20641231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20640101-20641231.nc' 'SHA256' '2feadf94d10957a679fd5cea1d2d724c08885c1e44d8fe38a08bdcee6f0dc606'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20650101-20651231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20650101-20651231.nc' 'SHA256' 'c77237d69bc27c92d5a10eafe2fa6d7cad3fea9019174fea764989c6969de51a'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20660101-20661231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20660101-20661231.nc' 'SHA256' '0f7dd101fc4ab0f94e48a75682e9280599cecd4ede7b737734b7620761bb0e0e'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20670101-20671231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20670101-20671231.nc' 'SHA256' '4295db67f644602d8e42f8acb97281f86be8ef437e55036729d361e375bb435d'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20680101-20681231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20680101-20681231.nc' 'SHA256' '8673091842817553ffbc31057946c24ac9d1fe9806b27b01e18da1f80c1afe31'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20690101-20691231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20690101-20691231.nc' 'SHA256' '9fda6d8c205f75d5bdcd69d0cf390a6c856dd9ac894c197e92aeebcd8fc62f85'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20700101-20701231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20700101-20701231.nc' 'SHA256' '7b4054f3c28e453cec5f8b82800172a39504596dcba85ce0b887a27b161105e6'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20710101-20711231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20710101-20711231.nc' 'SHA256' '18765667ad034ac9fea5298454d7576ea7af0968f016bc6ddfe0945cb39444f1'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20720101-20721231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20720101-20721231.nc' 'SHA256' '46f8a364293963177a8e75136476504790258fd04a5472337fd4aefdbd63bd2c'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20730101-20731231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20730101-20731231.nc' 'SHA256' '12e4d0588f9c637ecc28c7d796d5de5fcedcdd4eed51f678c647b0463a9dfce9'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20740101-20741231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20740101-20741231.nc' 'SHA256' 'bf394c6b1ad77a4070845a3029837ac936419a8505a858088eaf1b31219206db'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20750101-20751231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20750101-20751231.nc' 'SHA256' 'e3e39a69ca0c1c2f6e01001e65e65752ca00f9c5cd89ec2f94c4e12e8afbcfef'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20760101-20761231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20760101-20761231.nc' 'SHA256' '12b769db19bfb0ac6f60771f97d1819fdfdb901d5c06e1c5181aeeafa07adede'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20770101-20771231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20770101-20771231.nc' 'SHA256' 'ab04c47d4d6e96b848e395ba40a170230ffa6b6a89858b556be1988586b5d843'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20780101-20781231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20780101-20781231.nc' 'SHA256' '7674c8ee8776a8e46bb9afb99b89e3295d7cf769809b19cd961de82007acd2db'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20790101-20791231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20790101-20791231.nc' 'SHA256' '9c9a01b675501d4bc07d6b9e2ecfa36bcd2e1a87559ef775ef5d5a0b49515b59'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20800101-20801231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20800101-20801231.nc' 'SHA256' '165f50540ca770341595bc8a740a77a23a283c889f5ee9fc65a6d3f179c20934'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20810101-20811231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20810101-20811231.nc' 'SHA256' 'b85bef2b44a4fdbafe4d35efbd5d8d529afbf794eaf89517aaf5a0589597276f'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20820101-20821231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20820101-20821231.nc' 'SHA256' '0442b7237547dfb4b5889f9e489a4a490e7c19b694f7447780d3ffe2c2958d14'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20830101-20831231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20830101-20831231.nc' 'SHA256' '2222fb0fed21cb1ad3cddd9da384e57c90d06121eb69c3fdff2e57bc35ed6b23'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20840101-20841231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20840101-20841231.nc' 'SHA256' '3cc8c71b6f778cc093634172a1768da1982bba5523bb117d391356169f7b7ea3'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20850101-20851231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20850101-20851231.nc' 'SHA256' 'dc8d7a1b6b2d290a084e04da5eff4ca71217eec2e6abe53e835f7b691b9cb5c2'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20860101-20861231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20860101-20861231.nc' 'SHA256' 'd7404b7886fc72ca856af7493e92e5585fb37417603f6898e94416ca9b3987e4'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20870101-20871231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20870101-20871231.nc' 'SHA256' '8494ea3e3299f63644b41486c690a68191cf96fbb35732af78d68da148cd58d3'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20880101-20881231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20880101-20881231.nc' 'SHA256' '7955750855180437bffce6349a148b5282d4e4ec694aee09cf4d7f1c086d5c2e'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20890101-20891231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20890101-20891231.nc' 'SHA256' 'd5555feb6b89794475112f645515d705fce444fa15351e64ad25aca586ccbaac'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20900101-20901231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20900101-20901231.nc' 'SHA256' 'a4adbcf92bf84e3b8a2cc854a6d919dfcd944faceec0ee78cc5b19aebd20b10a'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20910101-20911231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20910101-20911231.nc' 'SHA256' 'a8fb078306fe0d833880f5be211881e6e14ab3032e498cd895b2ab8f88eaaeb0'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20920101-20921231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20920101-20921231.nc' 'SHA256' '4e03462b09b01ca5d2fa9f68febbf5680181c8208c500df13926230854de49df'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20930101-20931231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20930101-20931231.nc' 'SHA256' '1b095589f52c0a134e8a54f18ed3091b5abf180bba2815e888ab5cc24c098c6b'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20940101-20941231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20940101-20941231.nc' 'SHA256' '8803f135ea14891808f3b95fe6409c8445e304b776e2dc7a31bde2b2129e585d'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20950101-20951231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20950101-20951231.nc' 'SHA256' '7ed7c6851dfe4b50e63efd85d46121565248f5d0d8dd38dbd71f8a5bae7494ed'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20960101-20961231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20960101-20961231.nc' 'SHA256' '87325076dfb554255e32e0b4b962606361d8f59aee073e92903fc15995a851c8'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20970101-20971231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20970101-20971231.nc' 'SHA256' 'b13933ee3d308ce32912fd2cf15cd3f0b6239efeeed27a223c6553c66f990e6a'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20980101-20981231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20980101-20981231.nc' 'SHA256' '52a4e2612322f0c3811400ca25c94b6f755cfb4e7b4d2a3402fd9ee3d410ef13'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_20990101-20991231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_20990101-20991231.nc' 'SHA256' 'ebbde6993415620c9c090e1ccde81f76c1d1c4c1a96f6d8cf3ee009b03d3cb16'
'tos_day_MPI-ESM-MR_rcp85_r1i1p1_21000101-21001231.nc' 'http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MPI-M/MPI-ESM-MR/rcp85/day/ocean/day/r1i1p1/tos/1/tos_day_MPI-ESM-MR_rcp85_r1i1p1_21000101-21001231.nc' 'SHA256' 'f3a8caddbc99b260cbbb8df8b9c5781fbbabf36ba289213cf16024e1015abc73'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 285 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
